<?php
 /**
 * 2007-2025 PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 *
 * @author    yourName
 * @copyright 2007-2025 
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 * @generated by PrestashopConsole  / copyright 2016-2025 Hennes Hervé http://www.h-hennes.fr/blog/
 */
 

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Update module in version 0_5_0
 * @param Module $module
 */
function upgrade_module_0_5_0($module)
{
    return $module->registerHook('actionTranslationSave');
}
