services:
  _defaults:
    public: true

  #List of converters
  hhennes.modulesmanager.converter.configuration:
    class: Hhennes\ModulesManager\Converter\Configuration
    tags: [ hhennes.modulesmanager.converter ]
  hhennes.modulesmanager.converter.modules:
    class: Hhennes\ModulesManager\Converter\Module
    tags: [ hhennes.modulesmanager.converter ]
  hhennes.modulesmanager.converter.translation:
    class: Hhennes\ModulesManager\Converter\Translation
    tags: [ hhennes.modulesmanager.converter ]
  hhennes.modulesmanager.converter.factory:
    class: Hhennes\ModulesManager\Converter\ConverterFactory
    arguments:
      - !tagged hhennes.modulesmanager.converter
  #Management of converters
  hhennes.modulesmanager.patch.generator:
    class: Hhennes\ModulesManager\Patch\Generator
    arguments:
      - '@hhennes.modulesmanager.converter.factory'


  #List of upgraders
  hhennes.modulesmanager.upgrader.configuration:
    class: Hhennes\ModulesManager\Upgrader\Configuration
    tags: [ hhennes.modulesmanager.upgrader]
  hhennes.modulesmanager.upgrader.modules:
    class: Hhennes\ModulesManager\Upgrader\Module
    tags: [ hhennes.modulesmanager.upgrader ]
  hhennes.modulesmanager.upgrader.translation:
    class: Hhennes\ModulesManager\Upgrader\Translation
    arguments:
      - "@doctrine.orm.entity_manager"
    tags: [ hhennes.modulesmanager.upgrader ]
  hhennes.modulesmanager.upgrader.factory:
    class: Hhennes\ModulesManager\Upgrader\UpgraderFactory
    arguments:
      - !tagged hhennes.modulesmanager.upgrader

  #Management of the upgrade
  hhennes.modulesmanager.manager:
    class: Hhennes\ModulesManager\Patch\Manager
    arguments:
      - '@hhennes.modulesmanager.upgrader.factory'


  #Module upgrade filter in back office
  #Ne fonctionne qu'à partir de prestashop 8+ ...
  #Voir comment faire cohabiter les différentes versions
  #Car signatures différentes
#  hhennes.modulesmanager.adapter.admin.data_provider.module:
#    class: Hhennes\ModulesManager\Admin\ModuleDataProvider
#    decorates: prestashop.core.admin.data_provider.module_interface
#    arguments:
#      - "@prestashop.categories_provider"
#      - "@prestashop.adapter.data_provider.module"
#      - "@=service('prestashop.adapter.legacy.context').getContext().employee"
#    calls:
#      - [ setRouter, [ '@router' ] ]

  #Decorator for the translation service to dispatch the event
  hhennes.modulesmanager.service.translation:
    class: Hhennes\ModulesManager\Service\TranslationServiceWithHook
    decorates: prestashop.service.translation
    arguments:
      - "@prestashop.core.hook.dispatcher"
    properties:
      container: "@service_container"

  #Console commands
  hhennes.modulesmanager.manage.command:
    class: Hhennes\ModulesManager\Commands\ManageModulesCommand
    arguments:
      - '@hhennes.modulesmanager.manager'
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'
      - '@PrestaShop\PrestaShop\Core\Context\ContextBuilderPreparer'
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'
    tags:
      - { name: console.command }
  hhennes.modulesmanager.upgradable.modules.list:
    class: Hhennes\ModulesManager\Commands\ListUpgradableModulesCommand
    arguments:
      - '@PrestaShop\PrestaShop\Core\Module\ModuleRepository'
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'
      - '@PrestaShop\PrestaShop\Core\Context\ContextBuilderPreparer'
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'
    tags:
      - { name: console.command }
  hhennes.modulesmanager.upgrade.generate:
    class: Hhennes\ModulesManager\Commands\GeneratePatchCommand
    arguments:
      - '@hhennes.modulesmanager.patch.generator'
    tags:
      - { name: console.command }
  #Logger
  hhennes.modulesmanager.logger:
    class: 'Psr\Log\LoggerInterface'
    factory: [ '@hhennes.modulesmanager.logger.factory', 'build' ]
  hhennes.modulesmanager.logger.factory:
    class: 'Hhennes\ModulesManager\Logger\LoggerFactory'

  # Admin controller for Changes grid
  Hhennes\ModulesManager\Controller\Admin\ChangeController:
    class: Hhennes\ModulesManager\Controller\Admin\ChangeController

  # Grid services for Changes
  hhennes.modulesmanager.grid.definition.factory.change:
    class: Hhennes\ModulesManager\Grid\Definition\Factory\ChangeGridDefinitionFactory
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
    arguments:
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'

  hhennes.modulesmanager.grid.query.change.query_builder:
    class: Hhennes\ModulesManager\Grid\Query\ChangeQueryBuilder
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'

  hhennes.modulesmanager.grid.data.factory.change:
    class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
    arguments:
      - '@hhennes.modulesmanager.grid.query.change.query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'hhmodulesmanager_change'
    public: true

  hhennes.modulesmanager.grid.change.grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@hhennes.modulesmanager.grid.definition.factory.change'
      - '@hhennes.modulesmanager.grid.data.factory.change'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'